AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Emova - Analítica de Conversaciones

Globals:
  Function:
    Runtime: python3.11
    Timeout: 300
    MemorySize: 512
    Tags:
      Project: EMOVA
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Parameters:
  Environment:
    Type: String
    Default: dev
  AudioBucketName:
    Type: String
    Default: emova-audio-302263078976-dev

Resources:
  # API Gateway
  EmovaApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub emova-api-${Environment}
      StageName: !Ref Environment
      Tags:
        Project: EMOVA

  # Lambda: Analizar audio (transcribe + bedrock)
  AnalyzeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub emova-analyze-${Environment}
      Handler: analyze_handler.handler
      CodeUri: src/
      Timeout: 600
      Environment:
        Variables:
          AUDIO_BUCKET: !Ref AudioBucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AudioBucketName
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - transcribe:StartTranscriptionJob
                - transcribe:GetTranscriptionJob
              Resource: '*'
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
      Events:
        AnalyzeApi:
          Type: Api
          Properties:
            RestApiId: !Ref EmovaApi
            Path: /analyze
            Method: post

  # Lambda: Obtener URL presignada para upload
  UploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub emova-upload-url-${Environment}
      Handler: upload_handler.handler
      CodeUri: src/
      Environment:
        Variables:
          AUDIO_BUCKET: !Ref AudioBucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AudioBucketName
      Events:
        UploadApi:
          Type: Api
          Properties:
            RestApiId: !Ref EmovaApi
            Path: /upload-url
            Method: get

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub https://${EmovaApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
  AnalyzeFunctionArn:
    Description: Lambda de análisis
    Value: !GetAtt AnalyzeFunction.Arn
